### ISSUE TITLE
Definir quais dados serão lidos

### ISSUE THREAD

**Issue by RobertoDebarba** [RobertoDebarba/distributed-flood-monitoring-system#3]

**Comment by matheushoeltgebaum** [comment]
[Dados.txt](https://github.com/RobertoDebarba/distributed-flood-monitoring-system/files/1086451/Dados.txt)

**Comment by RobertoDebarba** [comment]
River Level {
	"level": 10.5,
	"time": "2017-06-04T20:42Z",
	"riverName": "Rio Itajaí-Açú",
	"city": "Blumenau",
	"federativeUnit": "Santa Catarina"
}

Dam {
	"id": 0
	"damName": "Ituporanga",
	"city": "Ituporanga",
	"federativeUnit": "Santa Catarina"
	"capacity": 31,
	"floodgates": 7
}

Dam Level {
	"damId": 0
	"time": "2017-06-04T20:42Z",
	"level": 31.5
}

Floodgate {
	"damId": 0
	"time": "2017-06-04T20:42Z",
	"status": 1
}

Rainfall Index {
	"city": "Blumenau",
	"federativeUnit": "Santa Catarina",
	"stationName": "Araranguá",
	"time": "2017-06-04T20:42Z",
	"intensity": 7.5
}
